[package]
name = "clock-macro"
version = "0.1.0"
authors = ["Mike Mozalkov <mozalkovmd@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.81"
quote = "1.0.10"
proc-macro2 = "1.0.32"

[dev-dependencies]
snafu = "0.6.10"